SAOnlineMart/Controllers/CartController.cs
using Microsoft.AspNetCore.Mvc;
using SAOnlineMart.Data;
using SAOnlineMart.Services.Implementation;
using SAOnlineMart.ViewModels;

namespace SAOnlineMart.Controllers
{
    public class CartController : Controller
    {
        private readonly AppDbContext _context;

        private readonly IHttpContextAccessor _httpContextAccessor;

        public CartController(AppDbContext context, IHttpContextAccessor httpContextAccessor)
        {

            _context = context;
            _httpContextAccessor = httpContextAccessor;
        }


        //
        // GET: /ShoppingCart/
        public ActionResult Index()
        {
            var cart = CartActions.GetCart(_context, _httpContextAccessor);

            // Set up view model
            var viewModel = new ShoppingCartViewModel
            {
                //Get the cart items and their total
                CartItems = cart.GetCartItems(),
                CartTotal = cart.GetTotal()
            };

            // Set CartCount for the partial view
            ViewData["CartCount"] = cart.GetCartItems().Count();

            // Return the view
            return View(viewModel);
        }

        //
        // GET: /ShoppingCart/CartSummary
        public ActionResult CartSummary()
        {
            var cart = CartActions.GetCart(_context, _httpContextAccessor);

            ViewData["CartCount"] = cart.GetCount();

            return PartialView("CartSummary");
        }

        public IActionResult AddToCart(Guid productId)
        {
            var addedProduct = _context.Products.Single(
                product => product.Id == productId
                );

            var cart = CartActions.GetCart(_context, _httpContextAccessor);

            cart.AddToCart(addedProduct);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> RemoveFromCart(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var cartModel = await _context.Carts.FindAsync(id);

            if (cartModel != null)
            {
                _context.Carts.Remove(cartModel);
            }
            await _context.SaveChangesAsync();

            return RedirectToActionPermanent(nameof(Index));
        }
    }
}

SAOnlineMart/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SAOnlineMart.Data;
using SAOnlineMart.Models;
using SAOnlineMart.Services.Interface;

namespace SAOnlineMart.Controllers
{
    [Authorize(Roles = "Admin")] //Only the admin is authorized to make use of product actions
    public class ProductsController : Controller
    {
        private readonly AppDbContext _context;

        private readonly IFileService _fileService;
        private readonly IProductRepoService _productRepoService;

        public ProductsController(AppDbContext context, IFileService fileService, IProductRepoService productRepoService)
        {
            _context = context;
            _fileService = fileService;
            _productRepoService = productRepoService;
        }

        // GET: Products
        public async Task<IActionResult> Index()
        {
            return View(await _context.Products.ToListAsync());
        }

        // GET: Products/Details/5
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productsModel = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id);
            if (productsModel == null)
            {
                return NotFound();
            }

            return View(productsModel);
        }

        // GET: Products/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([FromForm][Bind("Id,ProductName,PriceIncents,ProductImage,ItemDescription,IsAvailableToBuy,CreateAt,UpdateAt")] ProductsModel productsModel, IFormFile ProductImage)
        {
            if (ProductImage != null) //If the image is not null then save it
            {
                var fileResult = _fileService.SaveImage(ProductImage);

                if (fileResult.Item1 == 1) // if the file result returns true then set the product image
                {
                    productsModel.ProductImage = fileResult.Item2; //Get name of image
                }
            }
            var productResult = _productRepoService.Add(productsModel); //Return weather the product has been added or not

            if (productResult) //Debugging block
            {
                Console.WriteLine("Added successfully");
            }
            else
            {
                Console.WriteLine("Add Failed");
            }
            if (ModelState.IsValid) //If the submitted values are all filled in 
            {

                productsModel.Id = Guid.NewGuid(); //Generate a product ID
                productsModel.CreateAt = DateTime.Now; //Set the created at date

                _context.Add(productsModel); //Add to database
                await _context.SaveChangesAsync(); //Save those changes

            }
            return RedirectToAction(nameof(Index)); //Return the user back to the product management page


            // return View(productsModel);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productsModel = await _context.Products.FindAsync(id);
            if (productsModel == null)
            {
                return NotFound();
            }
            return View(productsModel);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Guid id, [Bind("Id,ProductName,PriceIncents,ProductImage,ItemDescription,IsAvailableToBuy,CreateAt,UpdateAt")] ProductsModel productsModel, IFormFile ProductImage)
        {
            if (id != productsModel.Id)
            {
                return NotFound();
            }

            //Model state is returning false for these attributes, remove them from the model state check
            ModelState.Remove("ImageFile");
            ModelState.Remove("ProductImage");

            if (ModelState.IsValid) //If the required values are all present
            {
                if (ProductImage == null) //In the event the product image does not need to be changed
                {
                    var existingProduct = await _context.Products.AsNoTracking().FirstOrDefaultAsync(p => p.Id == id);

                    productsModel.ProductImage = existingProduct.ProductImage; //Set the product image to what we have saved already
                }
                else //In the even a new image has been chosen
                {
                    var existingProduct = await _context.Products.AsNoTracking().FirstOrDefaultAsync(p => p.Id == id); //Grab our existing product

                    _fileService.DeleteImage(existingProduct.ProductImage); //Delete the image file

                    var fileResult = _fileService.SaveImage(ProductImage); //Save the new image

                    if (fileResult.Item1 == 1)
                    {
                        productsModel.ProductImage = fileResult.Item2; //Get name of image
                    }
                    var productResult = _productRepoService.Add(productsModel); //Add the edited product back
                }

                try
                {
                    var existingProduct = await _context.Products.AsNoTracking().FirstOrDefaultAsync(p => p.Id == id); //Get our existing product

                    
                    productsModel.CreateAt = existingProduct.CreateAt; //Set created at value to the existing products value
                    
                    productsModel.UpdateAt = DateTime.Now;

                    _context.Update(productsModel);

                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductsModelExists(productsModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(productsModel);
        }

        // GET: Products/Delete/5
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var productsModel = await _context.Products
                .FirstOrDefaultAsync(m => m.Id == id); //Get product ID
            if (productsModel == null)
            {
                return NotFound();
            }

            return View(productsModel);
        }

        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var productsModel = await _context.Products.FindAsync(id); //Find product id
            
            if (productsModel != null) //If it exists
            {
                var fileResult = _fileService.DeleteImage(productsModel.ProductImage);//Delete the image file

                _context.Products.Remove(productsModel); //Remove from database
            }

            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        private bool ProductsModelExists(Guid id)
        {
            return _context.Products.Any(e => e.Id == id);
        }
    }
}

SAOnlineMart/Views/Shared/PageNotFound.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "PageNotFound";
}
<div class="col-md-12 text-center">
    <h1>404</h1>
    <h2>Page Not Found</h2>
    <p>
        Sorry, the page you are looking
        for does not exist.
    </p>
</div>

SAOnlineMart/Views/Shared/_CartSummary.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

@Html.ActionLink("Cart(" + ViewData["CartCount"] + ")", "Index", "Cart", new { id = "cart-status" })

SAOnlineMart/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SAOnlineMart</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SAOnlineMart.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SAOnlineMart</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>

                        <!--If the user is an admin then show these nav bar -->
                        @if (User.IsInRole("Admin")) 
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Products" asp-action="Index">Products</a>
                            </li>
                        }

                    </ul>
                    <partial name="_LoginPartial" /> <!--Add the login view as a partial view for the site nav bar-->

                    <partial name="_CartSummary" /> <!--Add the Cart index view as a partial view for the site nav bar-->
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - SAOnlineMart - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>